import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  tutorialSidebar: [
    {
      type: "category",
      label: "Intro",
      collapsed: false,
      items: ["intro"],
    },
    ,
    // {
    //   type: "category",
    //   label: "Tutorial-basics",
    //   collapsed: false,
    //   items: ["tutorial-basics/congratulations"],
    // },
    {
      type: "category",
      label: "Introduction",
      collapsed: false,
      items: [
        "introduction/what-is-bruno",
        "introduction/manifesto",
        "introduction/feedback-and-community",
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Bruno Basics",
          collapsed: false,
          items: [
            "getting-started/bruno-basics/download",
            "getting-started/bruno-basics/create-a-collection",
            "getting-started/bruno-basics/creating-a-request",
            "getting-started/bruno-basics/create-test", // Added Create a Test
            "getting-started/bruno-basics/run-a-collection", // Added Run a Collection
          ], // ✅ Download is inside Bruno Basics
        },
        {
          type: "category",
          label: "Import or Export Data",
          items: [
            "getting-started/import-or-export-data/exporting-collections",
            "getting-started/import-or-export-data/importing-collections",
            "getting-started/import-or-export-data/migrating-from-postman", // Added Migrating from Postman
            "getting-started/import-or-export-data/scripts-translator",
          ],
        },
        {
          type: "category",
          label: "Variables",
          collapsed: false,
          items: [
            "getting-started/variables/variables-overview",
            "getting-started/variables/global-variables",
            "getting-started/variables/environment-variables",
            "getting-started/variables/collection-variables",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
